version: '2.1'

services:

  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BUILDDOC=${BUILDDOC:-OFF}
        - BUILDSWIG=${BUILDSWIG:-OFF}
        - BUILDSWIGPYTHON=${BUILDSWIGPYTHON:-OFF}
        - BUILDSWIGJAVA=${BUILDSWIGJAVA:-OFF}
        - BUILDSWIGNODE=${BUILDSWIGNODE:-OFF}
        - USBPLAT=${USBPLAT:-OFF}
        - FIRMATA=${FIRMATA:-OFF}
        - ONEWIRE=${ONEWIRE:-OFF}
        - JSONPLAT=${JSONPLAT:-OFF}
        - IMRAA=${IMRAA:-OFF}
        - FTDI4222=${FTDI4222:-OFF}
        - IPK=${IPK:-OFF}
        - RPM=${RPM:-OFF}
        - ENABLEEXAMPLES=${ENABLEEXAMPLES:-ON}
        - INSTALLGPIOTOOL=${INSTALLGPIOTOOL:-OFF}
        - INSTALLTOOLS=${INSTALLTOOLS:-OFF}
        - BUILDTESTS=${BUILDTESTS:-ON}
        - CC=${CC:-clang-3.8}
        - CXX=${CXX:-clang++-3.8}
        - NODE_VERSION=${NODE_VERSION:-v4.4.7}
        - BUILDARCH=${BUILDARCH}
        - MRAA_SRC_DIR=${MRAA_SRC_DIR:-/usr/src/app}
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - SONAR_TOKEN
      - SONAR_ORG
      - SONAR_PROJ_KEY
      - MRAA_SRC_DIR=/usr/src/app
      - TRAVIS_PULL_REQUEST
      - TRAVIS_REPO_SLUG
      - GITHUB_TOKEN

  doc:
    extends: main
    build:
      args:
        - BUILDDOC=ON
    command: bash -c "make doc"

  python2:
    extends: main
    build:
      args:
        - BUILDSWIG=ON
        - BUILDSWIGPYTHON=ON
    command: bash -c "make _python2-mraa && ctest --output-on-failure"

  python3:
    extends: python2
    command: bash -c "make _python3-mraa && ctest --output-on-failure"

  java:
    extends: main
    build:
      args:
        - BUILDSWIG=ON
        - BUILDSWIGJAVA=ON
        - CC=gcc-4.8
        - CXX=g++-4.8
    command: bash -c "make mraajava && ctest --output-on-failure"

  node4:
    extends: main
    build:
      args:
        - BUILDSWIG=ON
        - BUILDSWIGNODE=ON
        - NODE_VERSION=v4.4.7
    command: bash -c "source /root/.nvm/nvm.sh && make npmpkg && cd .. && node-gyp configure && node-gyp build && npm test"

  node5:
    extends: node4
    build:
      args:
        - NODE_VERSION=v5.12.0

  sonar-scan:
    extends: main
    build:
      args:
        - BUILDSWIG=ON
        - BUILDSWIGPYTHON=ON
        - BUILDSWIGNODE=ON
        - BUILDSWIGJAVA=ON
        - ONEWIRE=ON
        - JSONPLAT=ON
    command: bash -c "build-wrapper-linux-x86-64 --out-dir $${MRAA_SRC_DIR}/build/bw-output make all && ./sonar-scan.sh"
#    command: bash -c "build-wrapper-linux-x86-64 --out-dir $${MRAA_SRC_DIR}/build/bw-output make all &&
#                      sonar-scanner --debug
#                        -Dsonar.projectKey=$${SONAR_PROJ_KEY}
#                        -Dsonar.projectBaseDir=$${MRAA_SRC_DIR}
#                        -Dsonar.sources=$${MRAA_SRC_DIR}
#                        -Dsonar.inclusions='api/**/*,CMakeLists.txt,examples/**/*,imraa/**/*,include/**/*,src/**/*,tests/**/*'
#                        -Dsonar.coverage.exclusions='**/*'
#                        -Dsonar.cfamily.build-wrapper-output=$${MRAA_SRC_DIR}/build/bw-output
#                        -Dsonar.host.url=https://sonarqube.com
#                        -Dsonar.organization=$${SONAR_ORG}
#                        -Dsonar.login=$${SONAR_TOKEN}
#                        -Dsonar.analysis.mode=preview
#                        -Dsonar.github.pullRequest=$${TRAVIS_PULL_REQUEST}
#                        -Dsonar.github.repository=$${TRAVIS_REPO_SLUG}
#                        -Dsonar.github.oauth=$${GITHUB_TOKEN}
#                     "
